### ISSUE TITLE
Can you add a Suffix component to the TextField and PasswordField?

### ISSUE THREAD

**Issue by Jordao9280** [DJ-Raven/raven-project#1]
Hi Ra, how are you?

- Can you add a component to clean the inserted text in a the #TextField?
- Also for see what was inserted in the #PasswordField, and another one to clean the inserted text (in this case 2 components), similar to addind a Suffix:

[https://www.youtube.com/watch?v=e-alyzToVlY](url)
(Java GUI - Suffix and Prefix Icon in Textfield)

**Comment by DJ-Raven** [comment]
OK I will

**Comment by dolamasa1** [comment]
u thank u sir keep going your great work
